### ISSUE TITLE
[Validation] Improve BaseRule's translation method

### ISSUE THREAD

**Issue by aedart** [aedart/athenaeum#114]
## Description

The `\Aedart\Validation\Rules\BaseRule::trans()` method has a hard-coded translation path prefix, which makes it kind of useless when working with this "base" outside the package itself.

## Possible solution

The prefix path SHOULD be customisable, perhaps via a getter / setter. Or at the very least as a protected class property.

**Comment by cavallefano** [comment]
hi, is possibile to work on it or is already assigned?

**Comment by aedart** [comment]
Hi @cavallefano 

If you are up for the challenge, feel free to submit a pull request.
