### ISSUE TITLE
[7.19] AntiVirus: Missing dependency on validation or missing docs

### ISSUE THREAD

**Issue by tminich** [aedart/athenaeum#176]
## Description

InfectionFreeFile extends BaseValidationRule (from the validation package). So either the anitvirus package needs to depend on the validation package or it should be mentioned in the docs that if you want to use the InfectionFreeFile rule you also need to install the validation package.

**Comment by aedart** [comment]
Hi @tminich. Thank for your report. I can confirm that the package is missing a dependency to `aedart/athenaeum-validation` of the same version.
I will create fix for this, as soon as possible (_this week_).

**Comment by aedart** [comment]
Fixed in version `7.20.0`
