### ISSUE TITLE
HttpClient debug needs a rewind

### ISSUE THREAD

**Issue by kernelguy** [aedart/athenaeum#19]
When using the new debug() functionality on a HttpClient request, it reads the body contents of of the response, causing sub sequential calls to getBody()->getContents() to return nothing.

Found by:
$response = $client->post($url, $payload);
json_decode($response->getBody()->getContents(), JSON_THROW_ON_ERROR);

**Comment by aedart** [comment]
Fixed by rewinding the Http message stream, before it is serialized for debugging or logging.
