### ISSUE TITLE
Support for "same-site" policy in Guzzle's Set-Cookie instance

### ISSUE THREAD

**Issue by aedart** [aedart/athenaeum#8]
**Describe the Feature**
The current `SetCookie` component from Guzzle does not support the [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies) directive, which the Athenaeum Cookies packages does.

**Possible Solution**
Create a pull request on Guzzle Http and add support for this directive.
If it's accepted, the change the `\Aedart\Http\Clients\Requests\Builders\Guzzle\CookiesHelper::convertFromGuzzle` to support it.

**Comment by aedart** [comment]
It appears that the SameSite directive is actually stored inside the `SetCookie`. To obtain it, one has to use the `toArray()` method, which is fine for now. But, this should be easier to obtain, using a getter - just like all other directives.

**Comment by paveljanda** [comment]
Any update on that?
